package com.newsmanagementsystem.model.enums;

public enum Scope {
    MARMARA_REGION,
    AEGEAN_REGION,
    BLACK_SEA_REGION,
    MEDITERRANEAN_REGION,
    CENTRAL_ANATOLIA_REGION,
    EASTERN_ANATOLIA_REGION,
    SOUTHEASTERN_ANATOLIA_REGION
}
